FROM alpine:latest
RUN apk add --update nodejs npm
WORKDIR /challenge2-hard/
COPY . /challenge2-hard
RUN npm install && npm run build
RUN npm test
RUN mkdir -p /var/www && cp -r /app/out /var/www/
RUN npm prune --production
CMD ["npm", "start"]
