pipeline {
  agent any
  stages {
    stage('Build and Push Image') {
      steps {
        script {
          def registryCredentials = [
            [$class: 'UsernamePasswordMultiBinding', credentialsId: 'DOCKER_HUB_CREDENTIALS', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']
          ]
          docker.withRegistry('https://registry.hub.docker.com', registryCredentials) {
            def image = docker.build("docker_username/challenge2:${env.BUILD_NUMBER}")
            image.push()
          }
        }
      }
    }
    stage('Deploy to Environment') {
      environment {
        SERVICE_PORT = '8080'
        ENVIRONMENT_VARIABLE = '-e SERVICE_PORT=8080 -e JAVA_OPTS=-Djenkins.install.runSetupWizard=false -e JENKINS_USER=ICC -e JENKINS_PASS=totallyNotSecurePasswordForLocalTesting!1337'
      }
      steps {
        sh "kubectl set env deployment/challenge2 ${ENVIRONMENT_VARIABLE}"
      }
    }
  }
}
