pipeline {
  agent any
  stages {
    stage('Build and Push Image') {
      steps {
        script {
          def registryCredentials = [
            [$class: 'UsernamePasswordMultiBinding', credentialsId: 'DOCKER_HUB_CREDENTIALS', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']
          ]
          docker.withRegistry('https://registry.hub.docker.com', registryCredentials) {
            def image = docker.build("docker_username/challenge2:${env.BUILD_NUMBER}")
            image.push()
          }
        }
      }
    }
    stage('Deploy to Environment') {
      environment {
        SERVICE_PORT = '8080'
        ENVIRONMENT_VARIABLE = 'dev JAVA_OPTS=-Djenkins.install.runSetupWizard=false JENKINS_USER=ICC JENKINS_PASS=totallyNotSecurePasswordForLocalTesting!1337'
      }
      steps {
        sh "kubectl set env deployment/challenge2 -e ${ENVIRONMENT_VARIABLE}"
        sh "kubectl expose deployment/challenge2 --port=${SERVICE_PORT} --target-port=${SERVICE_PORT} --type=LoadBalancer"
      }
    }
  }
}
